### ISSUE TITLE
Initial KEEP Migration Checklist

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#167]
- [ ] Manually migrate institutions
- [ ] manually migrate collection objects
- [ ] add CAS users for collection contribs/owners
- [ ] assign correct permissions to collection contribs/owners
- [ ] Copy files from repository filestore to libfile
- [ ] run migrate:import
- [ ] Load checksums into riprap
- [ ] add redirects in django to new collections and items
- [ ] disable collections in legacy repository
- [ ] Point handles to new urls
- [ ] Run riprap to verify checksums
- [ ] Delete extra copy on libfile after checksum verification

**Comment by elizoller** [comment]
I'm going to close this because this mega-issue doesn't do the work justice.
