### ISSUE TITLE
Epic : ISLE-ification

### ISSUE THREAD

**Issue by seth-shaw-asu** [asulibraries/islandora-repo#574]
Supersedes #271 to establish a new local, staging, and production build environment using [github.com/Islandora-Devops/isle-dc](https://github.com/Islandora-Devops/isle-dc/) .

- [ ] Local Development Site
  - [x] Fork [github.com/Islandora-Devops/isle-dc](https://github.com/Islandora-Devops/isle-dc/) ([ours](https://github.com/asulibraries/isle-dc)) and [isle-buildkit](https://github.com/Islandora-Devops/isle-buildkit/) ([ours](https://github.com/asulibraries/isle-buildkit/)) with branches for local customizations and branch [islandora-repo](https://github.com/asulibraries/islandora-repo) for necessary code and configuration changes.
  - [X] Drupal container running KEEP locally
  - [X] Drupal container running PRISM locally along-side KEEP
  - [x] #591
  - [x] Ensure all other services are working properly
    - [x] #593
    - [x] #594
    - [x] #595
    - [x] #596
    - [x] #597
    - [x] #598
  - [x] #600
  - [x] #601
- [ ] Staging Site
  - [x] #609
  - [ ] Make tools and procedures for backup and recovery
  - [ ] Make tools and procedures for pushing updates from local development to staging
  - [ ] Make procedures for migrating Fedora 5 to Fedora 6
  - [ ] #599; update code for Fedora 6 (and optionally for local dev)
- [ ] Migrate Production
  - [ ] Test migrating Drupal production content to new docker site (to catch bugs and better estimate content freeze window)
  - [ ] Test migrating Fedora production content to new docker site (to catch bugs and better estimate content freeze window)

**Comment by seth-shaw-asu** [comment]
Instead of the git subproject I decided to create a custom.Makefile with a command to download our islandora-repo as the codebase folder. E.g. `make clone-codebase BRANCH=isle`.

**Comment by seth-shaw-asu** [comment]
I can spin up most of the components of KEEP and PRISM locally now. I'm currently working on getting RipRap up and running.
